spring.application.name=api-gateway
server.port=${PORT:8080}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
spring.cloud.gateway.discovery.locator.enabled= false
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=https://pawpal-microservices.onrender.com
spring.cloud.gateway.routes[0].predicates[0]=Path=/user-service/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1