spring.application.name=api-gateway
server.port=${PORT:8080}

spring.cloud.gateway.discovery.locator.enabled= false

eureka.client.enabled=false

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=https://pawpal-microservices.onrender.com
spring.cloud.gateway.routes[0].predicates[0]=Path=/user-service/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1